version: 2.1

orbs:
  github-status: assurance-maladie-digital/github-status@1.3.0

executors:
  php-executor:
    docker:
      - image: cimg/php:8.2
    resource_class: medium

jobs:
  test:
    docker:
      - image: cimg/php:8.2
      - image: cimg/postgres:17.0
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
    steps:
      - checkout

      # Update GitHub status to pending
      - github-status/update:
          status: "pending"
          context: "ci/circle: Laravel Tests"
          description: "Tests are running..."
      
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      
      - run:
          name: Install Dependencies
          command: |
            composer install --no-progress --prefer-dist --no-interaction --no-scripts --no-suggest

      - save_cache:
          paths:
            - vendor
          key: composer-v1-{{ checksum "composer.lock" }}

      - run:
          name: Set Up Environment Variables
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan jwt:secret
            echo "DB_CONNECTION=pgsql" >> .env
            echo "DB_HOST=127.0.0.1" >> .env
            echo "DB_PORT=5432" >> .env
            echo "DB_DATABASE=test_db" >> .env
            echo "DB_USERNAME=test_user" >> .env
            echo "DB_PASSWORD=test_pass" >> .env

      - run:
          name: Run Database Migrations
          command: php artisan migrate --force

      - run:
          name: Run Laravel Tests
          command: php artisan test

      # Update GitHub status to success on test success
      - github-status/update:
          status: "success"
          context: "ci/circle: Laravel Tests"
          description: "Tests passed!"

      # If any command fails, update GitHub status to failure
      - run:
          name: Update GitHub Status on Failure
          command: |
            echo "Updating GitHub status to failure"
          when: on_fail
      - github-status/update:
          status: "failure"
          context: "ci/circle: Laravel Tests"
          description: "Tests failed!"
          when: on_fail

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      # Update GitHub status to pending
      - github-status/update:
          status: "pending"
          context: "ci/circle: Deployment"
          description: "Deployment in progress..."

      - add_ssh_keys:
          fingerprints:
            - "SHA256:zvuo567ZQyOTTi0BDMRoal+EAjVFaY3OTvTptn1QNGA"

      - run:
          name: Deploy Laravel App
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_SERVER "bash -c '
              echo \"Starting Laravel deployment...\";
              sudo systemctl daemon-reload;
              sudo systemctl restart laravel-deploy.service;
              echo \"Deployment process completed!\";
            '"
          
      # Update GitHub status to success on deployment success
      - github-status/update:
          status: "success"
          context: "ci/circle: Deployment"
          description: "Deployment successful!"
      
      # If deployment fails, update GitHub status
      - run:
          name: Update GitHub Status on Failure
          command: |
            echo "Updating GitHub status to failure"
          when: on_fail
      - github-status/update:
          status: "failure"
          context: "ci/circle: Deployment"
          description: "Deployment failed!"
          when: on_fail

  deploy-prod:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      # Update GitHub status to pending
      - github-status/update:
          status: "pending"
          context: "ci/circle: Production Deployment"
          description: "Deployment in progress to production..."

      - add_ssh_keys:
          fingerprints:
            - "SHA256:zvuo567ZQyOTTi0BDMRoal+EAjVFaY3OTvTptn1QNGA"

      - run:
          name: Deploy Laravel App to production
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_SERVER "bash -c '
              echo \"Starting Laravel deployment to production...\";
              cd /var/www/html/Reconcile-AI-BE-main
              git pull origin main

              composer install --no-interaction --prefer-dist --no-dev
              php artisan jwt:secret

              php artisan optimize:clear

              php artisan migrate --force
              sudo systemctl restart nginx
              echo \"Deployment process completed to production!\";
            '"
          
      # Update GitHub status to success on deployment success
      - github-status/update:
          status: "success"
          context: "ci/circle: Production Deployment"
          description: "Deployment successful to production!"
      
      # If deployment fails, update GitHub status
      - run:
          name: Update GitHub Status on Failure to production
          command: |
            echo "Updating GitHub status to failure to production"
          when: on_fail
      - github-status/update:
          status: "failure"
          context: "ci/circle: Production Deployment"
          description: "Deployment failed to production!"
          when: on_fail

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only:
                - main