version: 2.1

executors:
  php-executor:
    docker:
      - image: cimg/php:8.2
    resource_class: medium

jobs:
  test:
    docker:
      - image: cimg/php:8.2
      - image: cimg/postgres:16
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update && sudo apt install -y unzip libpq-dev
            composer install --no-progress --prefer-dist --no-interaction
      - run:
          name: Set Up Environment Variables
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan jwt:secret
            echo "DB_CONNECTION=pgsql" >> .env
            echo "DB_HOST=127.0.0.1" >> .env
            echo "DB_PORT=5432" >> .env
            echo "DB_DATABASE=test_db" >> .env
            echo "DB_USERNAME=test_user" >> .env
            echo "DB_PASSWORD=test_pass" >> .env
      - run:
          name: Run Database Migrations
          command: php artisan migrate --force
      - run:
          name: Run Laravel Tests
          command: php artisan test

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:zvuo567ZQyOTTi0BDMRoal+EAjVFaY3OTvTptn1QNGA"
      - run:
          name: Deploy Laravel App
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_SERVER '\<<EOF'
            echo "Starting Laravel deployment..."
            sudo systemctl daemon-reload
            sudo systemctl restart laravel-deploy.service
            echo "Deployment process completed!"
            EOF

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
                - main