name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: versioning
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: auto
          WITH_V: true

  deployment:
    needs: [tag_release]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            # Stop the Laravel server in tmux session 1
            tmux send-keys -t 1 C-c
            sleep 2 # Wait for the server to stop

            # Kill any remaining processes on port 8000
            kill -9 $(lsof -t -i :8000)

            # Navigate to the repository directory
            cd /var/www/html/Reconcile-AI-BE

            # Pull the latest changes
            git pull origin dev

            # Install Composer dependencies
            composer install --no-interaction --prefer-dist

            # Run database migrations (if needed)
            # php artisan migrate --force

            # Start the Laravel server in tmux session 1
            # tmux send-keys -t 1 "php artisan serve --host=0.0.0.0 --port=8000" C-m

            sudo systemctl restart nginx

            echo "Deployment complete. Laravel server is running."
