name: Deployment
on:
  push:
    branches:
      - main
      - dev
  # workflow_run:
  #   workflows: ["CI Testing"]  # 🚀 This runs ONLY after CI workflow completes
  #   types:
  #     - completed  # Runs when CI finishes (success or failure)
jobs:
  deployment:
    runs-on: reconcile
    timeout-minutes: 10
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      # - uses: actions/checkout@v4
      - name: Deploy to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # port: 22
          script: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "Starting Laravel deployment for production..."
              # cd /var/www/html/BE-main
              #  echo "🚀 Starting Main Processor..."
              bash /usr/local/bin/main.sh
              echo "✅ New Staging Processor started successfully."
              
            else
              # echo "Starting Laravel deployment for staging..."
              # # Start the deployment service (using explicit sudo with NOPASSWD permission)
              # cd /var/www/html/staging
              echo "Starting Processor..."
              bash /usr/local/bin/staging_be_processor.sh
            fi


