name: Testing

on:
  pull_request:
    branches: [main, dev] # Runs for same-repo PRs
    types: [opened, synchronize]
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  deployment:
    runs-on: reconcile
    timeout-minutes: 10


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout the PR branch
          persist-credentials: false



      - name: Run Tests on Remote VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} << 'EOF'
          
          # Navigate to project directory
          cd /home/Reconcile/runner-be

          # Fetch latest changes
          git fetch --all

          # Checkout the branch from the PR
          git checkout ${{ github.head_ref }}

          # Reset and pull the latest code from the branch
          git reset --hard origin/${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

          # Install dependencies
          composer install --no-progress --prefer-dist --no-interaction

          # Set environment variables
          cp .env.example .env
          php artisan key:generate
          php artisan jwt:secret
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_USERNAME=test_user" >> .env
          echo "DB_PASSWORD=test_pass" >> .env

          # Run migrations
          php artisan migrate --force

          # Run Laravel tests
          php artisan test

          EOF
